### ISSUE TITLE
Error with failing tests

### ISSUE THREAD

**Issue by janbaer** [blacksonic/angular2-es6-starter#6]
Whenever a test is failing there is a long call stack in the console. Could this be prevented in any way?

```
[15:48:15] Error: 1
    at formatError (/Users/jan.baer/.nvm/versions/node/v4.2.2/lib/node_modules/gulp-cli/lib/versioned/^3.7.0/formatError.js:20:10)
    at Gulp.<anonymous> (/Users/jan.baer/.nvm/versions/node/v4.2.2/lib/node_modules/gulp-cli/lib/versioned/^3.7.0/log/events.js:41:15)
    at emitOne (events.js:82:20)
    at Gulp.emit (events.js:169:7)
    at Gulp.Orchestrator._emitTaskDone (/Users/jan.baer/temp/angular2-es6-starter/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /Users/jan.baer/temp/angular2-es6-starter/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/Users/jan.baer/temp/angular2-es6-starter/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
```

**Comment by blacksonic** [comment]
Does this solve the problem?
´´´
let server = new KarmaServer({
  configFile: configPath,
  singleRun: singleRun,
  autoWatch: !singleRun
}, function() {
  error = error ? new Error('Karma returned with the error code: ' + error) : undefined;
  done(error);
});
´´´

**Comment by janbaer** [comment]
No unfortunately not. I still see the whole callstack. I look some different on my Mac at home, but the code change made no change with the output. I think the error will be logged earlier.

```
  First test
    ✗ Should be true
        Expected true to equal false.
        stack@/Volumes/Macintosh HD 2/Projects/howcani/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1577:37
        buildExpectationResult@/Volumes/Macintosh HD 2/Projects/howcani/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1547:19
        expectationResultFactory@/Volumes/Macintosh HD 2/Projects/howcani/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:638:40
```

**Comment by blacksonic** [comment]
Managed to fix the formatError issue, but Gulp displays the call stack of the error by default.
The other interesting thing is the output of Karma:

```
PhantomJS 2.1.1 (Linux 0.0.0) PostService should return post FAILED
	Expected Object({ _id: 'asdgre', name: 'Angular', website: 'http://angular.io' }) to equal 'test'.
	__tryOrSetError
	next
	_next
	next
	_next
	next
	_next
	next
	_subscribe
	subscribe
	_subscribe
	subscribe
	_subscribe
	subscribe
PhantomJS 2.1.1 (Linux 0.0.0): Executed 12 of 12 (1 FAILED) (0.355 secs / 0.43 secs)
```

**Comment by blacksonic** [comment]
Created tickets for this strange call stack like error.
https://github.com/karma-runner/karma/issues/2024
https://github.com/angular/angular/issues/7783

**Comment by blacksonic** [comment]
Solved the weird call stack by replacing ```devtool : eval``` to ```devtool: inline-cheap-source-map``` in webpack test config, now errors displayed nicely.

**Comment by janbaer** [comment]
Thank you very much! The output is now a lot better...

**Comment by blacksonic** [comment]
The jasmine error stack can be improved with column numbers if you change it to ```inline-source-map``` but it will make the running of tests a bit slower.
